#!/bin/bash

echo -e "\n\n -- copying files on android -- \n\n" && \
adb push ./index.html /storage/emulated/0/Download/webview/index.html && \
adb push ./style.css /storage/emulated/0/Download/webview/style.css && \
adb push ./user.png /storage/emulated/0/Download/webview/user.png && \
adb push ./icon.ico /storage/emulated/0/Download/webview/icon.ico && \
echo -e "\n\n -- launching page view -- \n\n" && \
adb shell am start -a android.intent.action.VIEW -t "text/html" -c android.intent.category.DEFAULT -d "content://com.google.android.apps.nbu.files.provider/1/file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FDownload%2Fwebview%2Findex.html" -n "com.android.chrome/com.google.android.apps.chrome.Main"

##adb shell am start -a android.intent.action.VIEW -t "text/html" -c android.intent.category.DEFAULT -d "content://com.google.android.apps.nbu.files.provider/1/file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FDownload%2Fwebview%2Findex.html" -n "com.android.chrome/com.google.android.apps.chrome.Main"
##adb shell "am start -a android.intent.action.VIEW -t \"text/html\" -c android.intent.category.DEFAULT -d \"content://com.google.android.apps.nbu.files.provider/1/file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FDownload%2Fwebview%2Findex.html\" -n com.android.chrome/com.google.android.apps.chrome.Main --activity-clear-top --referrer \"android-app://com.google.android.apps.nbu.files.provider/1/file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FDownload%2Fwebview%2F\""
##adb shell "am start -a android.intent.action.VIEW -t \"text/html\" -c android.intent.category.DEFAULT -d \"content://com.google.android.apps.nbu.files.provider/1/file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FDownload%2Fwebview%2Findex.html\" -n \"com.android.chrome/com.google.android.apps.chrome.Main\" --activity-clear-top --esa \"android.intent.extra.REFERRER_NAME\" \"Name of Referrer\" --esa \"android.intent.extra.REFERRER\" \"android-app://com.google.android.apps.nbu.files\""
## adb shell "am start -a android.intent.action.VIEW -t \"text/html\" -c android.intent.category.DEFAULT -d \"content://com.google.android.apps.nbu.files.provider/1/file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FDownload%2Fwebview%2Findex.html\" -n \"com.android.chrome/com.google.android.apps.chrome.Main\" --activity-clear-top -e \"css\" \"/storage/emulated/0/Download/webview/style.css\""

##adb shell am start -n com.android.chrome/com.google.android.apps.chrome.Main -a android.intent.action.VIEW -t text/html -d "file:///sdcard/Download/webview/index.html"

##adb shell am start -a android.intent.action.VIEW -n org.mozilla.firefox/org.mozilla.gecko.BrowserApp -t text/html -d file:///data/local/tmp/index.html
