#!/bin/bash

echo -e "\n\n -- copying files on android -- \n\n" && \
adb push ./index.html /data/local/tmp/index.html && \
adb push ./style.css /data/local/tmp/style.css && \
adb push ./user.png /data/local/tmp/user.png && \
adb push ./icon.ico /data/local/tmp/icon.ico && \
echo -e "\n\n -- launching page view -- \n\n" && \
adb shell chmod +r /data/local/tmp/index.html && \
adb shell am start -a android.intent.action.VIEW -n org.mozilla.firefox/org.mozilla.gecko.BrowserApp -t text/html -d file:///data/local/tmp/index.html
